# Generated by Django 4.2.7 on 2024-01-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('books', '0003_alter_bookdata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdata',
            name='category',
            field=models.ManyToManyField(to='categories.category'),
        ),
    ]
